language: python

python:
  - "3.7-dev"  # 3.7 development branch

notifications:
  email: false

before_install:
# Begin by trying to build the docker images, just to check they are working...the images themselves are not used.
#  - docker build --no-cache=true -t "benblamey/haste_pipeline_worker_base:latest" ./worker/worker-base
  - docker build --no-cache=true -t "benblamey/haste_pipeline_worker:latest" ./worker
  - docker build --no-cache=true -t "benblamey/haste_pipeline_client:latest" ./client

install:
  - pip install ./worker
  - pip install ./client

script:
  - pytest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
